# This configmap is used by the cluster monitoring operator to configure prometheus remote write which is in charge of forwarding metrics to the Telemetry service.
#
#
# Every entry should be commented with a short description of the metric(s).
# It is also possible to mention the consumers (again handles preferred) so that
# any change to the metric can be communicated to the right audience.

# TODO: overhead of having multiple remote write entries
apiVersion: v1
data:
  remote_write.yaml: |-
    - url: https://infogw.api.stage.openshift.com/metrics/v1/receive
      name: openshift/openshift-team-monitoring
      writeRelabelConfigs:
        - sourceLabels: ["__name__"]
          regex: "cluster:usage:.*|count:up0|count:up1|"
          action: 'keep'
    - url: https://infogw.api.stage.openshift.com/metrics/v1/receive
      name: openshift/openshift-team-cincinnati
      writeRelabelConfigs:
        - sourceLabels: ["__name__"]
          regex: "cluster_version|cluster_version_available_updates|cluster_version_capability|cluster_operator_up|cluster_operator_conditions|cluster_version_payload"
          action: 'keep'
    - url: https://infogw.api.stage.openshift.com/metrics/v1/receive
      name: openshift/openshift-team-installer
      writeRelabelConfigs:
        - sourceLabels: ["__name__"]
          regex: "cluster_installer"
          action: 'keep'
    - url: https://infogw.api.stage.openshift.com/metrics/v1/receive
      name: openshift/openshift-team-master
      writeRelabelConfigs:
        - sourceLabels: ["__name__"]
          regex: "cluster_infrastructure_provider|cluster_feature_set"
          action: 'keep'
    - url: https://infogw.api.stage.openshift.com/metrics/v1/receive
      name: openshift/openshift-team-etcd
      writeRelabelConfigs:
        - sourceLabels: ["__name__"]
          regex: "instance:etcd_object_counts:sum"
          action: 'keep'
kind: ConfigMap
metadata:
  name: default-telemetry-remote-write-config
  namespace: openshift-monitoring