apiVersion: v1
data:
  metadata-profile.yaml: |-
    "apiVersion": "audit.k8s.io/v1"
    "kind": "Policy"
    "metadata":
      "name": "Metadata"
    "rules":
    - "level": "Metadata"
  none-profile.yaml: |-
    "apiVersion": "audit.k8s.io/v1"
    "kind": "Policy"
    "metadata":
      "name": "None"
    "omitStages":
    - "RequestReceived"
    "rules":
    - "level": "None"
  request-profile.yaml: |-
    "apiVersion": "audit.k8s.io/v1"
    "kind": "Policy"
    "metadata":
      "name": "Request"
    "omitStages":
    - "RequestReceived"
    "rules":
    - "level": "Request"
  requestresponse-profile.yaml: |-
    "apiVersion": "audit.k8s.io/v1"
    "kind": "Policy"
    "metadata":
      "name": "RequestResponse"
    "omitStages":
    - "RequestReceived"
    "rules":
    - "level": "RequestResponse"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
  name: metrics-server-audit-profiles
  namespace: openshift-monitoring
